# Introduction to JavaScript

WIP...pre spelling check

## Settings

Before getting started, let's set the development enviroment. There are many ways to develope and excute JavaScript, for this tutorial, I am using VScode. VScode has great integrations with JavaScript, HTML, and CSS, and seamless integration with Docker. In addition, it has great integration of Quarto, which used to create this document. If you want to follow the same settings, check the instractions below.

### VScode Settings for JavaScripts

If you don't have VScode install, you can download and install it directly from [VScode website](https://code.visualstudio.com/). I also using [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extention, which enables you to launch a local development server with live reload feature for static & dynamic pages. 

### Docker

**TODO**
Setting docker with VScode

The main reason I love using VScode is the seamless integression with Docker, enabling you develop in your local folder while running the code inside image. If you want to use the same environment here are two simple ways:


## Getting started with JavaScript

JavaScript (also known as JS), is one of the most popular programming lannguage for web development. It typically used to create web pages applications, mobile apps, games, and great data visualizations tools. You can run JavaScript on your web-browser (e.g., Chrome, Safari, Firefox, etc.):

**Screen record here***

While you can use your web-browser as consul for ad-hoc code test, the development of JS applications done inside a script using code editor such VScode, notepade, etc. It is common to have JS code embaded inside HTML script (or calling JS script from HTML script). Here is a basic example:

``` shell
.
├── index.html
├── index.js
└── style.ccs
```






